### ISSUE TITLE
Workspace Essentials

### ISSUE THREAD

**Issue by MahadMuhammad** [DrMahad/Learn-Assembly-The-Hard-Way#17]
# Create a workspace:
- Create a folder for workspace in which we save all the currenty working files & where nasm & DOSBOX resides
# Tasks: 😄 
- [x] Add **Hello.asm** in workspace folder, which prints `Hello World` on the screen.
- [x] Add README.md guidance in workspace folder.
- [x] Update **.gitignore** to ignore ***.com** & ***.conf** file
- [x] **Add AFD debugger** in README.md of Workspace folder.

**Comment by drmahad** [comment]
# Tasks

- [ ] Add Hello.asm in workspace folder.
